version: "3.9"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "8000:5173"
    environment:
      - BACKEND_API=http://api-server:3000
      - VITE_CLIENT_HOST_URL=http://localhost:8000
    volumes:
      - ./client:/usr/app
      - /usr/app/.git
    networks:
      - frontend
    depends_on:
      - api-server
  api-server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
      - /usr/app/.git
    environment:
      - DATABASE_URL=postgresql://root:1234@db:5432/root
      - REDIS_URL=redis://cache:6379
      - ACCESS_TOKEN_KEY=48b6e9e7c0498676d23dfe6a4435b667
      - ACCESS_TOKEN_EXPIRES_IN="1d"
    networks:
      - backend
      - frontend
    depends_on:
      - db
      - cache
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=root
    networks:
      - backend
    volumes:
      - ./server/prisma/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql/data
  cache:
    image: redis
    volumes:
      - cache:/data
    networks:
      - backend
networks:
  backend:
  frontend:
volumes:
  db:
  cache:
