version: "3.9"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:5173
    environment:
      - BACKEND_URL=http://api-server
    volumes:
      - ./client:/usr/app
      - /usr/app/node_modules
      - /usr/app/.git
    networks:
      - frontend
  api-server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3000
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
      - /usr/app/dist
      - /usr/app/.git
    env_file:
      - ./server/.env.dev
    environment:
      - DATABASE_URL=postgresql://root:1234@db:5432
      - REDIS_URL=redis://cache:6379
    networks:
      - backend
      - frontend
    depends_on:
      - db
      - cache
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=root
    networks:
      - backend
    volumes:
      - db:/var/lib/postgresql/data
  cache:
    image: redis
    volumes:
      - cache:/data
    networks:
      - backend
networks:
  backend:
  frontend:
volumes:
  db:
  cache:
